# Location of top-level MicroPython directory
MPY_DIR = ../micropython

# Name of module
MOD = uchess

# Source files (.c or .py)
SRC = uchess.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = x64

# Options to pass compiler
# CFLAGS = -static

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk

# LIBS += $(shell $(CC) $(CFLAGS) -print-libgcc-file-name)
